[project]
name = "plagiarism-detector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "plotly>=6.2.0",
    "sentence-transformers>=5.0.0",
    "streamlit>=1.46.1",
]
